---
title: "Freiburg experiments"
author: "Ruben Lopez"
date: "12/2/2021"
output: html_document
---




```{r}
pacman::p_load(readxl, here, ggplot2, dplyr, forcats, readr, tidyr, purrr, cowplot)
```

here i am loading the dataset...


### Enviroment management

```{r}
#renv::activate()
#renv::init() with init you start a new instance of renv inside the current folder, so only do it one time per project at the main working directory
renv::snapshot()
```


### Loading the raw data


```{r}

dirs <- "/Volumes/GroupOdening/Ruben/Experiment_Friburg/data" %>% 
  list.files(full.names = TRUE, pattern = "xlsx$", recursive = TRUE) #%>% 



dirs %>% 
  length()

dataframe <- dirs %>%
# dirs %>% 
  map_dfr( ~ read_xlsx(path = .x, 
                       sheet = 1)) %>% 
  mutate(across(where(is.character), factor)) %>% 
  mutate(MAP = factor(MAP)) %>% 
  mutate(Frequency = factor(Frequency)) %>% 
  mutate(Sex = factor(Sex)) %>% 
  mutate(Animal = factor(Animal))
                       # col_types = list(Animal = col_double())))


dataframe %>% 
  str
```




```{r}

# here()

# dataframe <- read_excel(path = here("OM_data", 
#                                     "OM data 1st week Ruben's version.xlsx"), 
#                         # col_types = list(Date = col_character()
#                           # Animal = col_factor(),
#                           # Genotype = col_factor(),
#                           # Sex = col_factor(),
#                           # Frequency = col_factor(),
#                           # Condition = col_factor(),
#                           # MAP = col_factor()
#                         # ),
#                         sheet = 1)
# dataframe %>% str()
  
```



```{r}

dataframe <- dataframe %>% 
  mutate(across(where(is.character), factor)) %>% 
  mutate(MAP = factor(MAP)) %>% 
  mutate(Frequency = factor(Frequency)) %>% 
  mutate(Sex = factor(Sex)) %>% 
  mutate(Animal = factor(Animal))

dataframe %>% 
  str



```





```{r}

dataframe %>% 
  ggplot(aes(x = Genotype,
             y = `APD 30`)) +
  geom_jitter(aes(color = Animal,
                  shape = MAP) ) + 
  facet_grid( Condition ~ Frequency)
  

```





averaging replicates of MAP measurements



```{r, }
average_apds_df <- dataframe %>% 
  nest(data =c(MAP, APD30, APD75, APD90)) %>% 
  mutate(data = map(data, ~ .x %>% 
                      group_by(MAP) %>% 
                      summarize(across(where(is.double), mean)))) %>% 
  unnest(cols = data) %>% 
  select(-Sex, -Observations)
```


```{r, fig.width= 6, fig.asp = 1.2}

average_apds_df %>% 
  drop_na(APD30) %>% # just temporal for visual
  # mutate(id = factor(rep(1:718))) %>% 
  ggplot(aes(x = Condition,
             y = APD30,
             # shape = Animal,
             group = Animal,
             color  = Animal)) +
  geom_line() + 
  geom_point() +
  facet_grid( MAP ~ Genotype + Frequency)

```


```{r, fig.width= 4, fig.asp = 1.2}

apds <- c("APD30", "APD75", "APD90")

apds %>% 
  map(~ ggplot(data = average_apds_df,
               aes_string(x = "Condition",
                          y = .x,
                          # shape = Animal,
                          group = "Animal",
                          color  = "Animal")) +
                 geom_line() + 
                 geom_point() +
                 facet_grid( MAP ~ Genotype + Frequency)) %>% 
  plot_grid(plotlist = .,
            cols = 1)
  
```


```{r}
dataframe %>% 
  nest(data =c(MAP, APD30, APD75, APD90)) %>% 
  mutate(data = map(data, ~ .x %>% 
                      group_by(MAP) %>% 
                      summarize(across(where(is.double), mean)))) %>% 
  unnest(cols = data) %>% 
  drop_na(!APD30)
```

